// <auto-generated />
using System;
using HighSchoolManagerment.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HighSchoolManagerment.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210524164820_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HighSchoolManagerment.Data.Entities.BangDiem", b =>
                {
                    b.Property<int>("MaBD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("CaNam")
                        .HasColumnType("float");

                    b.Property<double?>("DTBHK1")
                        .HasColumnType("float");

                    b.Property<double?>("DTBHK2")
                        .HasColumnType("float");

                    b.Property<double?>("Diem15PhutHK1")
                        .HasColumnType("float");

                    b.Property<double?>("Diem15PhutHK2")
                        .HasColumnType("float");

                    b.Property<double?>("Diem1TietHK1")
                        .HasColumnType("float");

                    b.Property<double?>("Diem1TietHK2")
                        .HasColumnType("float");

                    b.Property<double?>("DiemMiengHK1")
                        .HasColumnType("float");

                    b.Property<double?>("DiemMiengHK2")
                        .HasColumnType("float");

                    b.Property<double?>("DiemThiHK1")
                        .HasColumnType("float");

                    b.Property<double?>("DiemThiHK2")
                        .HasColumnType("float");

                    b.Property<int?>("MaHK")
                        .HasColumnType("int");

                    b.Property<int?>("MaHL")
                        .HasColumnType("int");

                    b.Property<string>("MaMH")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaND")
                        .HasColumnType("int");

                    b.Property<int?>("MaNH")
                        .HasColumnType("int");

                    b.HasKey("MaBD");

                    b.HasIndex("MaHK");

                    b.HasIndex("MaHL");

                    b.HasIndex("MaMH");

                    b.HasIndex("MaND");

                    b.ToTable("BangDiem");
                });

            modelBuilder.Entity("HighSchoolManagerment.Data.Entities.ChucNang", b =>
                {
                    b.Property<string>("MaCN")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IconCss")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaCNCha")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Url")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaCN");

                    b.ToTable("ChucNang");
                });

            modelBuilder.Entity("HighSchoolManagerment.Data.Entities.GioiTinh", b =>
                {
                    b.Property<int>("MaGT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ten")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaGT");

                    b.ToTable("GioiTinh");
                });

            modelBuilder.Entity("HighSchoolManagerment.Data.Entities.HanhKiem", b =>
                {
                    b.Property<int>("MaHK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ten")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaHK");

                    b.ToTable("HanhKiem");
                });

            modelBuilder.Entity("HighSchoolManagerment.Data.Entities.HocLuc", b =>
                {
                    b.Property<int>("MaHL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ten")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaHL");

                    b.ToTable("HocLuc");
                });

            modelBuilder.Entity("HighSchoolManagerment.Data.Entities.Lop", b =>
                {
                    b.Property<int>("MaLop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("NamHocMaNH")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLop");

                    b.HasIndex("NamHocMaNH");

                    b.ToTable("Lop");
                });

            modelBuilder.Entity("HighSchoolManagerment.Data.Entities.MonHoc", b =>
                {
                    b.Property<string>("MaMH")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaMH");

                    b.ToTable("MonHoc");
                });

            modelBuilder.Entity("HighSchoolManagerment.Data.Entities.NamHoc", b =>
                {
                    b.Property<int>("MaNH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ten")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaNH");

                    b.ToTable("NamHoc");
                });

            modelBuilder.Entity("HighSchoolManagerment.Data.Entities.NguoiDung", b =>
                {
                    b.Property<int>("MaND")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("MaGT")
                        .HasColumnType("int");

                    b.Property<int?>("MaLop")
                        .HasColumnType("int");

                    b.Property<string>("MaNND")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MaTG")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaND");

                    b.HasIndex("MaGT");

                    b.HasIndex("MaLop");

                    b.HasIndex("MaNND");

                    b.HasIndex("MaTG");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("HighSchoolManagerment.Data.Entities.NguoiDungLop", b =>
                {
                    b.Property<int>("MaND")
                        .HasColumnType("int");

                    b.Property<int>("MaLop")
                        .HasColumnType("int");

                    b.HasKey("MaND", "MaLop");

                    b.HasIndex("MaLop");

                    b.ToTable("NguoiDungLop");
                });

            modelBuilder.Entity("HighSchoolManagerment.Data.Entities.NhomNguoiDung", b =>
                {
                    b.Property<string>("MaNND")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaNND");

                    b.ToTable("NhomNguoiDung");
                });

            modelBuilder.Entity("HighSchoolManagerment.Data.Entities.TKB", b =>
                {
                    b.Property<int>("MaTKB")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Buoi")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MaLop")
                        .HasColumnType("int");

                    b.Property<string>("MaMH")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaNH")
                        .HasColumnType("int");

                    b.Property<string>("Thu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Tiet")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.HasKey("MaTKB");

                    b.HasIndex("MaLop");

                    b.HasIndex("MaMH");

                    b.HasIndex("MaNH");

                    b.ToTable("TKB");
                });

            modelBuilder.Entity("HighSchoolManagerment.Data.Entities.TonGiao", b =>
                {
                    b.Property<int>("MaTG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaTG");

                    b.ToTable("TonGiao");
                });

            modelBuilder.Entity("HighSchoolManagerment.Data.Quyen", b =>
                {
                    b.Property<string>("MaQ")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaQ");

                    b.ToTable("Quyen");
                });

            modelBuilder.Entity("HighSchoolManagerment.Data.VaiTro", b =>
                {
                    b.Property<string>("MaVT")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaNND")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserGroupId")
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaVT", "MaNND");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserGroupId");

                    b.ToTable("VaiTro");
                });

            modelBuilder.Entity("HighSchoolManagerment.Data.Entities.BangDiem", b =>
                {
                    b.HasOne("HighSchoolManagerment.Data.Entities.HanhKiem", "HanhKiem")
                        .WithMany()
                        .HasForeignKey("MaHK");

                    b.HasOne("HighSchoolManagerment.Data.Entities.HocLuc", "HocLuc")
                        .WithMany()
                        .HasForeignKey("MaHL");

                    b.HasOne("HighSchoolManagerment.Data.Entities.MonHoc", "MonHoc")
                        .WithMany()
                        .HasForeignKey("MaMH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HighSchoolManagerment.Data.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaND");

                    b.Navigation("HanhKiem");

                    b.Navigation("HocLuc");

                    b.Navigation("MonHoc");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("HighSchoolManagerment.Data.Entities.Lop", b =>
                {
                    b.HasOne("HighSchoolManagerment.Data.Entities.NamHoc", null)
                        .WithMany("Lops")
                        .HasForeignKey("NamHocMaNH");
                });

            modelBuilder.Entity("HighSchoolManagerment.Data.Entities.NguoiDung", b =>
                {
                    b.HasOne("HighSchoolManagerment.Data.Entities.GioiTinh", "GioiTinh")
                        .WithMany()
                        .HasForeignKey("MaGT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HighSchoolManagerment.Data.Entities.Lop", "Lop")
                        .WithMany()
                        .HasForeignKey("MaLop");

                    b.HasOne("HighSchoolManagerment.Data.Entities.NhomNguoiDung", "NhomNguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNND");

                    b.HasOne("HighSchoolManagerment.Data.Entities.TonGiao", "TonGiao")
                        .WithMany()
                        .HasForeignKey("MaTG")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GioiTinh");

                    b.Navigation("Lop");

                    b.Navigation("NhomNguoiDung");

                    b.Navigation("TonGiao");
                });

            modelBuilder.Entity("HighSchoolManagerment.Data.Entities.NguoiDungLop", b =>
                {
                    b.HasOne("HighSchoolManagerment.Data.Entities.Lop", "Lop")
                        .WithMany()
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HighSchoolManagerment.Data.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaND")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lop");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("HighSchoolManagerment.Data.Entities.TKB", b =>
                {
                    b.HasOne("HighSchoolManagerment.Data.Entities.Lop", "Lop")
                        .WithMany()
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HighSchoolManagerment.Data.Entities.MonHoc", "MonHoc")
                        .WithMany()
                        .HasForeignKey("MaMH");

                    b.HasOne("HighSchoolManagerment.Data.Entities.NamHoc", "NamHoc")
                        .WithMany("TKBs")
                        .HasForeignKey("MaNH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lop");

                    b.Navigation("MonHoc");

                    b.Navigation("NamHoc");
                });

            modelBuilder.Entity("HighSchoolManagerment.Data.VaiTro", b =>
                {
                    b.HasOne("HighSchoolManagerment.Data.Quyen", "Quyen")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.HasOne("HighSchoolManagerment.Data.Entities.NhomNguoiDung", "NhomNguoiDung")
                        .WithMany()
                        .HasForeignKey("UserGroupId");

                    b.Navigation("NhomNguoiDung");

                    b.Navigation("Quyen");
                });

            modelBuilder.Entity("HighSchoolManagerment.Data.Entities.NamHoc", b =>
                {
                    b.Navigation("Lops");

                    b.Navigation("TKBs");
                });
#pragma warning restore 612, 618
        }
    }
}
